CREATE INDEX idx_c_cuskey ON CUSTOMER(C_CUSTKEY);
CREATE INDEX idx_c_mk ON CUSTOMER(C_MKTSEGMENT);
CREATE INDEX idx_o_cuskey ON ORDERS(O_CUSTKEY);
CREATE INDEX idx_o_orderkey ON ORDERS(O_ORDERKEY);
CREATE INDEX idx_o_orderdate ON ORDERS(O_ORDERDATE);
CREATE INDEX idx_l_orderkey ON LINEITEM(L_ORDERKEY);
CREATE INDEX idx_l_shipdate ON LINEITEM(L_SHIPDATE);

CREATE INDEX i_P_partkey ON PART(P_PARTKEY);
CREATE INDEX i_S_suppkey ON SUPPLIER(S_SUPPKEY);
CREATE INDEX i_N_nationkey ON NATION(N_NATIONKEY);
CREATE INDEX i_regionkey On REGION(R_REGIONKEY);
CREATE INDEX i_S_nationkey ON SUPPLIER(S_NATIONKEY);
CREATE INDEX i_PS_suppkey ON PARTSUPP(PS_SUPPKEY);
CREATE INDEX i_P_typekey ON PART(P_TYPE);
CREATE INDEX i_P_sizekey ON PART(P_SIZE);
CREATE INDEX i_namekey ON REGION(R_NAME);

